import { Montserrat } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import BootstrapClient from "@/app/lib/BootstrapClient"; // ✅
import ConditionalNavbar from "@/app/components/ConditionalNavbar";
import ConditionalMainWrapper from "@/app/components/ConditionalMainWrapper";
import QueryProvider from "@/app/components/QueryProvider";
import { AuthProvider } from "@/app/context/AuthContext";
import SocketInitializer from "@/app/components/SocketInitializer";

import ConditionalFooter from "@/app/components/ConditionalFooter";
import dynamic from "next/dynamic";

const AIChatWidget = dynamic(() => import("@/components/chat/AIChatWidget"), {
  ssr: false
});

// Montserrat font with optimized subsets and weights
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-montserrat"
});

export const metadata = {
  icons: {
    icon: "/public/images/logo.ico"
  },
  title: "EGYGO TRAVEL APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <BootstrapClient /> {/* Loads Bootstrap JS safely on client */}
        <AuthProvider>
          <SocketInitializer /> {/* Initialize trip status socket connection */}
          <QueryProvider>
            <ConditionalNavbar />
            <ConditionalMainWrapper>
              {children}
            </ConditionalMainWrapper>
            <ConditionalFooter />
            <AIChatWidget />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
