import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import BootstrapClient from "@/app/lib/BootstrapClient"; // ✅
import Navbar from "@/app/components/Navbar";
import QueryProvider from "@/app/components/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    icons: {
    icon: "/public/images/logo.ico"},
  title: "EGYGO TRAVEL APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BootstrapClient /> {/* Loads Bootstrap JS safely on client */}
        <QueryProvider>
          <Navbar />
          <main style={{ paddingTop: '80px' }}>
            {children}
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
 